logging:
  level:
    root: info
server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-77192151.okta.com/oauth2/default/v1/keys
       
 
 #https://dev-77192151.okta.com/oauth2/default/.well-known/oauth-authorization-server